Host 101
    HostName fms.metsafr.com
    User uface
    Port 1222

Host 102
    HostName fms.metsafr.com
    User uface
    Port 1322

Host 102d
    HostName fms.metsafr.com
    User uface_docker
    Port 1322

Host 102tr
    HostName fms.metsafr.com
    User uface2_tr
    Port 1322

Host 103d
    HostName fms.metsafr.com
    User uface_docker
    Port 1422

Host 104
    HostName fms.metsafr.com
    User mkfr
    Port 1522

Host 85
    HostName fms.metsafr.com
    User docker
    Port 1022

Host caddy
    HostName fms.metsafr.com
    User mkfr
    Port 38222

Host ktnf
    HostName 222.122.77.74
    User uface
    Port 22
